CREATE DATABASE IF NOT EXISTS `webgpio`;

USE `webgpio`;

DROP TABLE IF EXISTS `users`;

CREATE TABLE  `users`
(
`id`			INT(11) NOT NULL auto_increment,
`username`		VARCHAR(255) NOT NULL,
`password`		VARCHAR(255) NOT NULL,
`name`			VARCHAR(255) NOT NULL,
`created_at`	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET=latin1;
